figure
for viz = 1:size(SwrEvents,1)
    ripple_visualize(SwrEvents(viz,1),...
        SwrEvents(viz,2),...
        LFP,...
        SpkInfo{g,2}(a).L_chn{3}(1),...
        1);
    pause(1)
end % for ripple viz